apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

# Update namespace for staging deployment
namespace: kustomizedemo-dev

# Generates a config map with the hash values and update all deployment whereever it is referenced
configMapGenerator:
  - name: kustomizedemo
    files:
      - nginx-config/nginx.conf

# Example how you can use variables dynamically
vars:
- name: CM_NAME
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kustomizedemo
  fieldref:
    fieldpath: metadata.name

configurations:
- kustomizeconfig/varreference.yaml
