apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../prod

# Update namespace for staging deployment
namespace: kustomizedemo-prod

secretGenerator:
- name: app-tls
  files:
  - secret/tls.crt
  - secret/tls.key
  type: "kubernetes.io/tls"

# - name: app-tls-namespaced
#   # you can define a namespace to generate
#   # a secret in, defaults to: "default"
#   namespace: apps
#   files:
#   - tls.crt=catsecret/tls.crt
#   - tls.key=secret/tls.key
#   type: "kubernetes.io/tls"

- name: env_file_secret
  envs:
  - secret/env.txt
  type: Opaque
- name: secret-with-annotation
  files:
  - secret/app-config.yaml
  type: Opaque
  options:
    annotations:
      app_config: "true"
    labels:
      app.kubernetes.io/name: "app2"