apiVersion: v1
kind: Service
metadata:
  name: kustomizedemo
spec:
  selector:
    app: kustomizedemo
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      nodePort: 30080
  type: NodePort